title: My WildCat Studios Portfolio description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://lm154406.github.io" # replace YOURUSERNAME with your GitHub username
remote_theme: pages-themes/midnight@v0.2.0
